name: LuckyBounties
version: 1.4.1
main: de.lucky44.luckybounties.LuckyBounties
api-version: 1.14

permissions:
  lb.op:
    default: op
    description: Allows use of operator features of this plugin


commands:
  bounties:
    aliases: b
    description: show bounties menu
    usage: /bounties